steps:
  # Build and Push Monolithic Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-store-lookup', '.']
    id: 'build-app'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/app-store-lookup']
    id: 'push-app'
    waitFor: ['build-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'app-store-lookup'
      - '--image'
      - 'gcr.io/$PROJECT_ID/app-store-lookup'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
    id: 'deploy-app'
    waitFor: ['push-app']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/app-store-lookup'
